name: douyin
description: "Study douyin project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/pngs/
    - assets/jpgs/

  fonts:
    - family: 汉仪篆书繁
      fonts:
        - asset: assets/fonts/汉仪篆书繁.ttf

    - family: 思源黑体
      fonts:
        - asset: assets/fonts/SourceHanSansSC-ExtraLight-2.otf
