name: douyin
description: "Study douyin project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  get: ^4.6.6
  get_storage: ^2.1.1
  build_runner: ^2.4.14
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  js: ^0.7.1
  flutter_staggered_grid_view: ^0.7.0
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3+4
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/pngs/
    - assets/jpgs/

  fonts:
    - family: 汉仪篆书繁
      fonts:
        - asset: assets/fonts/汉仪篆书繁.ttf

    - family: 思源黑体
      fonts:
        - asset: assets/fonts/SourceHanSansSC-ExtraLight-2.otf

    - family: 青鸟华光繁仿宋
      fonts:
        - asset: assets/fonts/QingNiaoHuaGuangFanFangSong-2.ttf

    - family: 鼎猎宋刻体
      fonts:
        - asset: assets/fonts/dingliesongtypeface20241217-2.ttf

    - family: 鼎猎伙伴体
      fonts:
        - asset: assets/fonts/dingliehuobanfont20241217-2.ttf

    - family: 周字方体
      fonts:
        - asset: assets/fonts/ZhouZiFangTi241010-TTF-2.ttf

    - family: 鼎猎珠海体
      fonts:
        - asset: assets/fonts/dingliezhuhaifont-20240831GengXinBan)-2.ttf

    - family: 周字宋体
      fonts:
        - asset: assets/fonts/ZhouZiSongTi7000Zi-2.otf

    - family: 猫啃忘形圆
      fonts:
        - asset: assets/fonts/MaoKenWangXingYuan-2.ttf

    - family: 文鼎PL简报宋
      fonts:
        - asset: assets/fonts/gbsn00lp-2.ttf

    - family: 文鼎PL细上海宋
      fonts:
        - asset: assets/fonts/bsmi00lp-2.ttf

    - family: 小可奶酪体
      fonts:
        - asset: assets/fonts/XiaoKeNaiLaoTiShangYongMianFei@QingKeZiTi-2.ttf

    - family: 飞花宋体
      fonts:
        - asset: assets/fonts/FeiHuaSongTi-2.ttf

    - family: 三极素纤简体
      fonts:
        - asset: assets/fonts/SanJiSuXianJianTi-2.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf

    - family: Crystal
      fonts:
        - asset: assets/fonts/Crystal-Regular-2.ttf

    - family: NoteScript-Regular
      fonts:
        - asset: assets/fonts/Note-Script-Regular-2.ttf

    - family: NoteScript-SemiBold
      fonts:
        - asset: assets/fonts//Note-Script-SemiBold-2.ttf

