import 'dart:convert';

import 'package:json_annotation/json_annotation.dart';

import '../../../../../utils/icon_util.dart';

part 'model.g.dart';

/// CreateDate: 2025/1/16 17:26
/// Author: Lee
/// Description:

@JsonSerializable()
class ExperienceEntity {
  const ExperienceEntity({
    this.id,
    this.path,
    this.title,
    this.avatar,
    this.username,
    this.likeCount,
    this.height,
    this.time,
    this.comments,
  });

  factory ExperienceEntity.fromJson(Map<String, dynamic> json) =>
      _$ExperienceEntityFromJson(json);

  final int? id;
  final String? path;
  final String? title;
  final String? avatar;
  final String? username;
  final int? likeCount;
  final double? height;
  final String? time;
  final List<CommentEntity>? comments;

  Map<String, dynamic> toJson() => _$ExperienceEntityToJson(this);

  @override
  String toString() => jsonEncode(this);
}

const List<ExperienceEntity> experiences = [
  ExperienceEntity(
    id: 0,
    path: IconUtil.icon_010,
    title: '四妹没有死',
    avatar: IconUtil.icon_024,
    username: '拔剑自然神',
    likeCount: 2186,
    height: 240.0,
    time: '昨天 14:08',
    comments: [
      CommentEntity(
        avatar: IconUtil.icon_009,
        username: '明天会更好！',
        comment: '这电影很好看！',
        time: '昨天 15:06',
        area: '江苏',
        likeCount: 1080,
        unlikeCount: 2401,
      ),
      CommentEntity(
        avatar: IconUtil.icon_021,
        username: '贾不假',
        comment: '赞赞赞！',
        time: '昨天 19:57',
        area: '辽宁',
      ),
      CommentEntity(
        avatar: IconUtil.icon_010,
        username: 'lfflllby',
        comment: '赞赞赞！',
        time: '2小时前',
        area: '辽宁',
      ),
      CommentEntity(
        avatar: IconUtil.icon_012,
        username: '安然无恙',
        comment: '赞赞赞！',
        time: '昨天 18:56',
        area: '天津',
        likeCount: 451,
        unlikeCount: 82,
      ),
      CommentEntity(
        avatar: IconUtil.icon_009,
        username: '北方浪人',
        comment: '赞赞赞！',
        time: '昨天 15:07',
        area: '辽宁',
      ),
      CommentEntity(
        avatar: IconUtil.icon_028,
        username: '展翅的飞',
        comment: '赞赞赞！',
        time: '昨天 17:42',
        area: '辽宁',
      ),
      CommentEntity(
        avatar: IconUtil.icon_032,
        username: '阳光灿烂的日子',
        comment: '有钱！',
        time: '昨天 15:56',
        area: '黑龙江',
      ),
      CommentEntity(
        avatar: IconUtil.icon_032,
        username: '大雷子',
        comment: '女人看哪吒不是喜欢哪吒的镯子。就是喜欢敖丙他爹',
        time: '昨天 17:11',
        area: '黑龙江',
      ),
    ],
  ),
  ExperienceEntity(
    id: 1,
    path: IconUtil.icon_012,
    title: '林忆莲巡回演唱会厦门站来啦！',
    avatar: IconUtil.icon_021,
    username: '宋小宋 (团攻略)',
    likeCount: 8,
    height: 200.0,
  ),
  ExperienceEntity(
    id: 2,
    path: IconUtil.icon_025,
    title: '只有看过火影的才懂这一刻的杀伤力',
    avatar: IconUtil.icon_002,
    username: '飝',
    likeCount: 819,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 3,
    path: IconUtil.icon_036,
    title: '缘分落地生根是我们',
    avatar: IconUtil.icon_006,
    username: '方知有-',
    likeCount: 254,
    height: 214.0,
  ),
  ExperienceEntity(
    id: 4,
    path: IconUtil.icon_008,
    title: '四妹没有死',
    avatar: IconUtil.icon_029,
    username: '拔剑自然神',
    likeCount: 2186,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 5,
    path: IconUtil.icon_011,
    title: '小爷是魔 那又如何',
    avatar: IconUtil.icon_007,
    username: 'L',
    likeCount: 6,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 6,
    path: IconUtil.icon_034,
    title: '一只飞不出广东的鸭子的白切鸭做法',
    avatar: IconUtil.icon_004,
    username: '客家人爱美食',
    likeCount: 36,
    height: 242.0,
  ),
  ExperienceEntity(
    id: 7,
    path: IconUtil.icon_031,
    title: '小爷是魔 那又如何',
    avatar: IconUtil.icon_009,
    username: '小清浅浅',
    likeCount: 436,
    height: 214.0,
  ),
  ExperienceEntity(
    id: 8,
    path: IconUtil.icon_022,
    title: '志同道合',
    avatar: IconUtil.icon_018,
    username: '善善玩具',
    likeCount: 432,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 9,
    path: IconUtil.icon_023,
    title: '林忆莲的票竟然卖不出去？',
    avatar: IconUtil.icon_015,
    username: '顺顺丽丽',
    likeCount: 67,
    height: 280.0,
  ),
  ExperienceEntity(
    id: 10,
    path: IconUtil.icon_032,
    title: '#白切鸡 #地方特色美食',
    avatar: IconUtil.icon_036,
    username: '墨西哥',
    likeCount: 11,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 11,
    path: IconUtil.icon_037,
    title: '怀疑过龙族、怀疑过申公豹、怀疑过妖族、就没怀疑过喝了三鹿奶粉的大头娃娃',
    avatar: IconUtil.icon_027,
    username: '口袋里有糖@',
    likeCount: 26,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 12,
    path: IconUtil.icon_010,
    title: '四妹没有死',
    avatar: IconUtil.icon_024,
    username: '拔剑自然神',
    likeCount: 2186,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 13,
    path: IconUtil.icon_012,
    title: '林忆莲巡回演唱会厦门站来啦！',
    avatar: IconUtil.icon_021,
    username: '宋小宋 (团攻略)',
    likeCount: 8,
    height: 200.0,
  ),
  ExperienceEntity(
    id: 14,
    path: IconUtil.icon_025,
    title: '只有看过火影的才懂这一刻的杀伤力',
    avatar: IconUtil.icon_002,
    username: '飝',
    likeCount: 819,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 15,
    path: IconUtil.icon_036,
    title: '缘分落地生根是我们',
    avatar: IconUtil.icon_006,
    username: '方知有-',
    likeCount: 254,
    height: 214.0,
  ),
  ExperienceEntity(
    id: 16,
    path: IconUtil.icon_008,
    title: '四妹没有死',
    avatar: IconUtil.icon_029,
    username: '拔剑自然神',
    likeCount: 2186,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 17,
    path: IconUtil.icon_011,
    title: '小爷是魔 那又如何',
    avatar: IconUtil.icon_007,
    username: 'L',
    likeCount: 6,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 18,
    path: IconUtil.icon_034,
    title: '一只飞不出广东的鸭子的白切鸭做法',
    avatar: IconUtil.icon_004,
    username: '客家人爱美食',
    likeCount: 36,
    height: 242.0,
  ),
  ExperienceEntity(
    id: 19,
    path: IconUtil.icon_031,
    title: '小爷是魔 那又如何',
    avatar: IconUtil.icon_009,
    username: '小清浅浅',
    likeCount: 436,
    height: 214.0,
  ),
  ExperienceEntity(
    id: 20,
    path: IconUtil.icon_022,
    title: '志同道合',
    avatar: IconUtil.icon_018,
    username: '善善玩具',
    likeCount: 432,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 21,
    path: IconUtil.icon_023,
    title: '林忆莲的票竟然卖不出去？',
    avatar: IconUtil.icon_015,
    username: '顺顺丽丽',
    likeCount: 67,
    height: 280.0,
  ),
  ExperienceEntity(
    id: 22,
    path: IconUtil.icon_032,
    title: '#白切鸡 #地方特色美食',
    avatar: IconUtil.icon_036,
    username: '墨西哥',
    likeCount: 11,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 23,
    path: IconUtil.icon_037,
    title: '怀疑过龙族、怀疑过申公豹、怀疑过妖族、就没怀疑过喝了三鹿奶粉的大头娃娃',
    avatar: IconUtil.icon_027,
    username: '口袋里有糖@',
    likeCount: 26,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 24,
    path: IconUtil.icon_010,
    title: '四妹没有死',
    avatar: IconUtil.icon_024,
    username: '拔剑自然神',
    likeCount: 2186,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 25,
    path: IconUtil.icon_012,
    title: '林忆莲巡回演唱会厦门站来啦！',
    avatar: IconUtil.icon_021,
    username: '宋小宋 (团攻略)',
    likeCount: 8,
    height: 200.0,
  ),
  ExperienceEntity(
    id: 26,
    path: IconUtil.icon_025,
    title: '只有看过火影的才懂这一刻的杀伤力',
    avatar: IconUtil.icon_002,
    username: '飝',
    likeCount: 819,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 27,
    path: IconUtil.icon_036,
    title: '缘分落地生根是我们',
    avatar: IconUtil.icon_006,
    username: '方知有-',
    likeCount: 254,
    height: 214.0,
  ),
  ExperienceEntity(
    id: 28,
    path: IconUtil.icon_008,
    title: '四妹没有死',
    avatar: IconUtil.icon_029,
    username: '拔剑自然神',
    likeCount: 2186,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 29,
    path: IconUtil.icon_011,
    title: '小爷是魔 那又如何',
    avatar: IconUtil.icon_007,
    username: 'L',
    likeCount: 6,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 30,
    path: IconUtil.icon_034,
    title: '一只飞不出广东的鸭子的白切鸭做法',
    avatar: IconUtil.icon_004,
    username: '客家人爱美食',
    likeCount: 36,
    height: 242.0,
  ),
  ExperienceEntity(
    id: 31,
    path: IconUtil.icon_031,
    title: '小爷是魔 那又如何',
    avatar: IconUtil.icon_009,
    username: '小清浅浅',
    likeCount: 436,
    height: 214.0,
  ),
  ExperienceEntity(
    id: 32,
    path: IconUtil.icon_022,
    title: '志同道合',
    avatar: IconUtil.icon_018,
    username: '善善玩具',
    likeCount: 432,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 33,
    path: IconUtil.icon_023,
    title: '林忆莲的票竟然卖不出去？',
    avatar: IconUtil.icon_015,
    username: '顺顺丽丽',
    likeCount: 67,
    height: 280.0,
  ),
  ExperienceEntity(
    id: 34,
    path: IconUtil.icon_032,
    title: '#白切鸡 #地方特色美食',
    avatar: IconUtil.icon_036,
    username: '墨西哥',
    likeCount: 11,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 35,
    path: IconUtil.icon_037,
    title: '怀疑过龙族、怀疑过申公豹、怀疑过妖族、就没怀疑过喝了三鹿奶粉的大头娃娃',
    avatar: IconUtil.icon_027,
    username: '口袋里有糖@',
    likeCount: 26,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 36,
    path: IconUtil.icon_010,
    title: '四妹没有死',
    avatar: IconUtil.icon_024,
    username: '拔剑自然神',
    likeCount: 2186,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 37,
    path: IconUtil.icon_012,
    title: '林忆莲巡回演唱会厦门站来啦！',
    avatar: IconUtil.icon_021,
    username: '宋小宋 (团攻略)',
    likeCount: 8,
    height: 200.0,
  ),
  ExperienceEntity(
    id: 38,
    path: IconUtil.icon_025,
    title: '只有看过火影的才懂这一刻的杀伤力',
    avatar: IconUtil.icon_002,
    username: '飝',
    likeCount: 819,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 39,
    path: IconUtil.icon_036,
    title: '缘分落地生根是我们',
    avatar: IconUtil.icon_006,
    username: '方知有-',
    likeCount: 254,
    height: 214.0,
  ),
  ExperienceEntity(
    id: 40,
    path: IconUtil.icon_008,
    title: '四妹没有死',
    avatar: IconUtil.icon_029,
    username: '拔剑自然神',
    likeCount: 2186,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 41,
    path: IconUtil.icon_011,
    title: '小爷是魔 那又如何',
    avatar: IconUtil.icon_007,
    username: 'L',
    likeCount: 6,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 42,
    path: IconUtil.icon_034,
    title: '一只飞不出广东的鸭子的白切鸭做法',
    avatar: IconUtil.icon_004,
    username: '客家人爱美食',
    likeCount: 36,
    height: 242.0,
  ),
  ExperienceEntity(
    id: 43,
    path: IconUtil.icon_031,
    title: '小爷是魔 那又如何',
    avatar: IconUtil.icon_009,
    username: '小清浅浅',
    likeCount: 436,
    height: 214.0,
  ),
  ExperienceEntity(
    id: 44,
    path: IconUtil.icon_022,
    title: '志同道合',
    avatar: IconUtil.icon_018,
    username: '善善玩具',
    likeCount: 432,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 45,
    path: IconUtil.icon_023,
    title: '林忆莲的票竟然卖不出去？',
    avatar: IconUtil.icon_015,
    username: '顺顺丽丽',
    likeCount: 67,
    height: 280.0,
  ),
  ExperienceEntity(
    id: 46,
    path: IconUtil.icon_032,
    title: '#白切鸡 #地方特色美食',
    avatar: IconUtil.icon_036,
    username: '墨西哥',
    likeCount: 11,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 47,
    path: IconUtil.icon_037,
    title: '怀疑过龙族、怀疑过申公豹、怀疑过妖族、就没怀疑过喝了三鹿奶粉的大头娃娃',
    avatar: IconUtil.icon_027,
    username: '口袋里有糖@',
    likeCount: 26,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 48,
    path: IconUtil.icon_010,
    title: '四妹没有死',
    avatar: IconUtil.icon_024,
    username: '拔剑自然神',
    likeCount: 2186,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 49,
    path: IconUtil.icon_012,
    title: '林忆莲巡回演唱会厦门站来啦！',
    avatar: IconUtil.icon_021,
    username: '宋小宋 (团攻略)',
    likeCount: 8,
    height: 200.0,
  ),
  ExperienceEntity(
    id: 50,
    path: IconUtil.icon_025,
    title: '只有看过火影的才懂这一刻的杀伤力',
    avatar: IconUtil.icon_002,
    username: '飝',
    likeCount: 819,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 51,
    path: IconUtil.icon_036,
    title: '缘分落地生根是我们',
    avatar: IconUtil.icon_006,
    username: '方知有-',
    likeCount: 254,
    height: 214.0,
  ),
  ExperienceEntity(
    id: 52,
    path: IconUtil.icon_008,
    title: '四妹没有死',
    avatar: IconUtil.icon_029,
    username: '拔剑自然神',
    likeCount: 2186,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 53,
    path: IconUtil.icon_011,
    title: '小爷是魔 那又如何',
    avatar: IconUtil.icon_007,
    username: 'L',
    likeCount: 6,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 54,
    path: IconUtil.icon_034,
    title: '一只飞不出广东的鸭子的白切鸭做法',
    avatar: IconUtil.icon_004,
    username: '客家人爱美食',
    likeCount: 36,
    height: 242.0,
  ),
  ExperienceEntity(
    id: 55,
    path: IconUtil.icon_031,
    title: '小爷是魔 那又如何',
    avatar: IconUtil.icon_009,
    username: '小清浅浅',
    likeCount: 436,
    height: 214.0,
  ),
  ExperienceEntity(
    id: 56,
    path: IconUtil.icon_022,
    title: '志同道合',
    avatar: IconUtil.icon_018,
    username: '善善玩具',
    likeCount: 432,
    height: 240.0,
  ),
  ExperienceEntity(
    id: 57,
    path: IconUtil.icon_023,
    title: '林忆莲的票竟然卖不出去？',
    avatar: IconUtil.icon_015,
    username: '顺顺丽丽',
    likeCount: 67,
    height: 280.0,
  ),
  ExperienceEntity(
    id: 58,
    path: IconUtil.icon_032,
    title: '#白切鸡 #地方特色美食',
    avatar: IconUtil.icon_036,
    username: '墨西哥',
    likeCount: 11,
    height: 220.0,
  ),
  ExperienceEntity(
    id: 59,
    path: IconUtil.icon_037,
    title: '怀疑过龙族、怀疑过申公豹、怀疑过妖族、就没怀疑过喝了三鹿奶粉的大头娃娃',
    avatar: IconUtil.icon_027,
    username: '口袋里有糖@',
    likeCount: 26,
    height: 240.0,
  ),
];

@JsonSerializable()
class CommentEntity {
  const CommentEntity({
    this.avatar,
    this.username,
    this.comment,
    this.time,
    this.area,
    this.likeCount,
    this.unlikeCount,
  });

  factory CommentEntity.fromJson(Map<String, dynamic> json) =>
      _$CommentEntityFromJson(json);

  final String? avatar;
  final String? username;
  final String? comment;
  final String? time;
  final String? area;
  final int? likeCount;
  final int? unlikeCount;

  Map<String, dynamic> toJson() => _$CommentEntityToJson(this);

  @override
  String toString() => jsonEncode(this);
}
